<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>PRmazing Jeepney Time Travel — Demo</title>
  <style>
    :root{font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,'Helvetica Neue',Arial;color:#111}
    body{margin:0;background:#f7f8fb;padding:24px;display:flex;gap:24px;flex-direction:column;align-items:center}
    .container{max-width:980px;width:100%;background:white;padding:20px;border-radius:14px;box-shadow:0 6px 20px rgba(16,24,40,.08)}
    header{display:flex;align-items:center;gap:16px}
    h1{margin:0;font-size:20px}
    p.lead{margin:6px 0 12px;color:#374151}
    .eras{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}
    .card{border-radius:12px;overflow:hidden;border:1px solid #eef2ff}
    .card img{width:100%;height:180px;object-fit:cover;background:#eee}
    .card .body{padding:12px}
    .btn{display:inline-block;padding:8px 12px;border-radius:8px;text-decoration:none;background:#4f46e5;color:white}
    .passport{margin-top:14px;padding:12px;border-radius:10px;background:#fcfbff;border:1px solid #eef2ff}
    .stamps{display:flex;gap:8px;flex-wrap:wrap}
    .stamp{padding:8px;border-radius:8px;background:white;border:1px dashed #c7d2fe;min-width:110px;text-align:center}
    .stamp.done{background:linear-gradient(90deg,#f0f9ff,#ecfeff);border-style:solid}
    .center{display:flex;justify-content:center;align-items:center}
    .confetti{font-size:18px;color:#16a34a}
    footer{margin-top:12px;color:#6b7280;font-size:13px}
    .era-detail{display:none}
    .era-detail.active{display:block}
    .qr-sample{display:flex;gap:10px;align-items:center}
    .note{font-size:13px;color:#6b7280}
    .danger{color:#b91c1c}
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div>
        <h1>PRmazing Jeepney Time Travel — Demo</h1>
        <p class="lead">Sumakay sa bawat era-jeep. Scan the QR inside the jeep (or open the era link) then press <strong>Confirm Ride</strong> to verify your location (1 km radius).</p>
      </div>
    </header>

    <section>
      <div class="eras" id="eras">
        <!-- Era cards generated by JS -->
      </div>

      <div class="passport" id="passport">
        <strong>Digital Passport</strong>
        <div class="stamps" id="stamps"></div>
        <div id="completeBox" style="display:none;margin-top:12px" class="center">
          <div>
            <div class="confetti">🎉 Congratulations — Journey Complete!</div>
            <div style="margin-top:8px"><a id="downloadCert" class="btn" href="#">Download Certificate</a></div>
          </div>
        </div>
      </div>

      <div style="margin-top:12px" class="note">Tip: For physical QR codes, generate QR that opens this page with <code>?era=ERA_SLUG</code> (example: <code>pr-demo.html?era=birth</code> or a hosted URL). The QR scanner should open the era page in the user's browser.</div>

    </section>

    <section class="era-detail" id="eraDetail">
      <div class="container">
        <button id="backBtn" class="btn" style="background:#ef4444">Back</button>
        <h2 id="eraTitle"></h2>
        <img id="eraImg" src="" alt="era" style="width:100%;height:260px;object-fit:cover;border-radius:10px;margin-top:8px"/>
        <p id="eraDesc"></p>
        <div style="display:flex;gap:12px;align-items:center">
          <button id="confirmRide" class="btn">Confirm Ride (checks location)</button>
          <span class="note">Current demo uses browser HTML5 geolocation. Allow location when prompted.</span>
        </div>
        <div id="rideMessage" style="margin-top:8px"></div>
        <hr />
        <div style="display:flex;gap:12px;align-items:center">
          <div class="qr-sample">
            <img id="qrImg" src="https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=demo" alt="qr"/>
            <div>
              <div class="note">Sample QR (replace with your QR generator). When scanning, it should open the same URL <code>?era=slug</code>.</div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <footer>
      <div>Demo notes: Images are placeholders (picsum). Replace images and set real jeep GPS coordinates in the <code>eras</code> array in the code. Progress is saved in localStorage.</div>
    </footer>
  </div>

<script>
// --- CONFIG: change these values to match your real jeeps ---
const eras = [
  {slug:'birth', title:'Birth of PR', desc:'The early beginnings — typewriters, pamphlets, and the first voices of public relations.', img:'https://picsum.photos/id/1062/800/500', lat:14.5910, lng:121.0000},
  {slug:'golden', title:'Golden Age of Media', desc:'Radio, television, and the mass media era that amplified messages to the public.', img:'https://picsum.photos/id/1011/800/500', lat:14.5920, lng:121.0015},
  {slug:'digital', title:'The Digital Shift', desc:'The internet and social media revolutionized PR into a 24/7 global conversation.', img:'https://picsum.photos/id/1005/800/500', lat:14.5930, lng:121.0030}
];
const RADIUS_METERS = 1000; // 1 km
// --- END CONFIG ---

const erasEl = document.getElementById('eras');
const stampsEl = document.getElementById('stamps');
const eraDetailEl = document.getElementById('eraDetail');
const eraTitle = document.getElementById('eraTitle');
const eraImg = document.getElementById('eraImg');
const eraDesc = document.getElementById('eraDesc');
const qrImg = document.getElementById('qrImg');
const rideMessage = document.getElementById('rideMessage');

// Load progress from localStorage
const STORAGE_KEY = 'pr_jeep_progress_v1';
let progress = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}');

function saveProgress(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(progress)); renderPassport(); }

function metersBetween(lat1,lon1,lat2,lon2){
  function toRad(x){return x*Math.PI/180}
  const R=6378137; // Earth radius in meters
  const dLat=toRad(lat2-lat1);const dLon=toRad(lon2-lon1);
  const a=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(toRad(lat1))*Math.cos(toRad(lat2))*Math.sin(dLon/2)*Math.sin(dLon/2);
  const c=2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a));
  return R*c;
}

function renderEras(){
  erasEl.innerHTML='';
  eras.forEach(e=>{
    const div=document.createElement('div');div.className='card';
    div.innerHTML=`<img src="${e.img}" alt="${e.title}"><div class="body"><h3 style='margin:0'>${e.title}</h3><p style='margin:8px 0;color:#6b7280'>${e.desc}</p><div style='display:flex;gap:8px'><a class='btn' href='?era=${e.slug}' data-slug='${e.slug}'>Open Era (QR link)</a><button class='btn' data-view='${e.slug}' style='background:#10b981'>View & Confirm</button></div></div>`;
    erasEl.appendChild(div);
  });
}

function renderPassport(){
  stampsEl.innerHTML='';
  eras.forEach(e=>{
    const s=document.createElement('div');s.className='stamp'+(progress[e.slug]? ' done':'');
    s.innerHTML=`<div><strong>${e.title}</strong></div><div style='font-size:12px;margin-top:6px'>${progress[e.slug]? '✔ Boarded':'— Not yet'}</div>`;
    stampsEl.appendChild(s);
  });
  const complete = eras.every(e=>progress[e.slug]);
  document.getElementById('completeBox').style.display = complete ? 'block' : 'none';
}

function openEra(slug){
  const e = eras.find(x=>x.slug===slug); if(!e) return;
  eraDetailEl.classList.add('active'); eraTitle.textContent=e.title; eraImg.src=e.img; eraDesc.textContent=e.desc;
  // update QR image to show link for this era (uses a public QR generator)
  const base = location.href.split('?')[0];
  const url = `${base}?era=${e.slug}`;
  qrImg.src = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(url)}`;
  rideMessage.innerHTML = '';
  document.getElementById('confirmRide').onclick = ()=>confirmRide(e);
}

function confirmRide(e){
  rideMessage.innerHTML = 'Requesting location — please allow browser location access...';
  if(!navigator.geolocation){ rideMessage.innerHTML = '<span class="danger">Location unavailable in this browser.</span>'; return; }
  navigator.geolocation.getCurrentPosition(pos=>{
    const lat=pos.coords.latitude, lon=pos.coords.longitude;
    const d = metersBetween(lat,lon,e.lat,e.lng);
    if(d <= RADIUS_METERS){
      progress[e.slug]=true; saveProgress(); rideMessage.innerHTML = `<span style="color:#16a34a">✔ You were verified within ${Math.round(d)} meters. Stamp added!</span>`;
    } else {
      rideMessage.innerHTML = `<span class="danger">✖ Verification failed — you are ${Math.round(d)} meters away (must be within ${RADIUS_METERS} m). Make sure you scan inside the jeep.</span>`;
    }
  }, err=>{
    rideMessage.innerHTML = '<span class="danger">Location permission denied or error. Ask users to allow location.</span>';
  }, {enableHighAccuracy:true,timeout:10000});
}

// UI wiring
renderEras(); renderPassport();

document.body.addEventListener('click', e=>{
  const view = e.target.getAttribute('data-view');
  if(view) openEra(view);
});

// back
document.getElementById('backBtn').onclick = ()=>{ eraDetailEl.classList.remove('active'); rideMessage.innerHTML=''; };

// if page opened with ?era=slug (like scanning QR) open automatically
(function checkQuery(){
  const params = new URLSearchParams(location.search);
  const era = params.get('era');
  if(era){ setTimeout(()=>openEra(era),300); }
})();

// Download certificate (simple generated image via canvas)
document.getElementById('downloadCert').onclick = function(e){
  e.preventDefault();
  const canvas = document.createElement('canvas'); canvas.width=1200; canvas.height=800; const ctx = canvas.getContext('2d');
  ctx.fillStyle='#ffffff'; ctx.fillRect(0,0,canvas.width,canvas.height);
  ctx.fillStyle='#111827'; ctx.font='36px serif'; ctx.fillText('PRmazing Jeepney Journey Certificate',60,120);
  ctx.font='24px serif'; ctx.fillText('Awarded to: Proud Traveler',60,200);
  const done = eras.filter(x=>progress[x.slug]).map(x=>x.title).join(', ');
  ctx.font='18px serif'; ctx.fillText('Completed eras: '+done,60,260);
  const data = canvas.toDataURL('image/png');
  const a = document.createElement('a'); a.href=data; a.download='prmazing_certificate.png'; a.click();
};

</script>
</body>
</html>
